spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq-demo
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db.migration
